import { Armor, Shield } from "../../core/domain/character/baseData/equipment"


export const paddedArmor: Armor = {
    uniqueId: "paddedArmor",
    name: "Padded Armor",
    arcaneSpellFailureChance: 5,
    armorCheckPenalty: 0,
    baseArmorBonus: 1,
    enhancementBonus: 0,
    maxDexBonus: 8,
    speed20: 20,
    speed30: 30,
    itemType: "ARMOR",
    weight: 10,
    description: "Padded Armor",
    cost: 5,
    equipped: true,
    equipable: true,
    enhancements: [],
}

export const leatherArmor: Armor = {
    uniqueId: "leatherArmor",
    name: "Leather Armor",
    arcaneSpellFailureChance: 10,
    armorCheckPenalty: 0,
    baseArmorBonus: 2,
    enhancementBonus: 0,
    maxDexBonus: 6,
    speed20: 20,
    speed30: 30,
    itemType: "ARMOR",
    weight: 15,
    description: "Leather Armor",
    cost: 10,
    equipped: true,
    equipable: true,
    enhancements: [],
}

export const studdedLeatherArmor: Armor = {
    uniqueId: "studdedLeatherArmor",
    name: "Studded Leather Armor",
    arcaneSpellFailureChance: 15,
    armorCheckPenalty: -1,
    baseArmorBonus: 3,
    enhancementBonus: 0,
    maxDexBonus: 5,
    speed20: 20,
    speed30: 30,
    itemType: "ARMOR",
    weight: 20,
    description: "Studded Leather Armor",
    cost: 25,
    equipped: true,
    equipable: true,
    enhancements: [],
}

export const chainShirtArmor: Armor = {
    uniqueId: "chainShirtArmor",
    name: "Chain Shirt Armor",
    arcaneSpellFailureChance: 20,
    armorCheckPenalty: -2,
    baseArmorBonus: 4,
    enhancementBonus: 0,
    maxDexBonus: 4,
    speed20: 20,
    speed30: 30,
    itemType: "ARMOR",
    weight: 25,
    description: "Chain Shirt Armor",
    cost: 100,
    equipped: true,
    equipable: true,
    enhancements: [],
}

export const hideArmor: Armor = {
    uniqueId: "hideArmor",
    name: "Hide Armor",
    arcaneSpellFailureChance: 20,
    armorCheckPenalty: -3,
    baseArmorBonus: 3,
    enhancementBonus: 0,
    maxDexBonus: 4,
    speed20: 15,
    speed30: 20,
    itemType: "ARMOR",
    weight: 25,
    description: "Hide Armor",
    cost: 15,
    equipped: true,
    equipable: true,
    enhancements: [],
}

export const scaleMailArmor: Armor = {
    uniqueId: "scaleMailArmor",
    name: "Scale Mail Armor",
    arcaneSpellFailureChance: 25,
    armorCheckPenalty: -4,
    baseArmorBonus: 4,
    enhancementBonus: 0,
    maxDexBonus: 3,
    speed20: 15,
    speed30: 20,
    itemType: "ARMOR",
    weight: 30,
    description: "Scale Mail Armor",
    cost: 50,
    equipped: true,
    equipable: true,
    enhancements: [],
}

export const chainMailArmor: Armor = {
    uniqueId: "chainMailArmor",
    name: "Chain Mail Armor",
    arcaneSpellFailureChance: 30,
    armorCheckPenalty: -5,
    baseArmorBonus: 5,
    enhancementBonus: 0,
    maxDexBonus: 2,
    speed20: 15,
    speed30: 20,
    itemType: "ARMOR",
    weight: 40,
    description: "Chain Mail Armor",
    cost: 150,
    equipped: true,
    equipable: true,
    enhancements: [],
}

export const breastplateArmor: Armor = {
    uniqueId: "breastplateArmor",
    name: "Breastplate Armor",
    arcaneSpellFailureChance: 25,
    armorCheckPenalty: -4,
    baseArmorBonus: 5,
    enhancementBonus: 0,
    maxDexBonus: 3,
    speed20: 15,
    speed30: 20,
    itemType: "ARMOR",
    weight: 30,
    description: "Breastplate Armor",
    cost: 200,
    equipped: true,
    equipable: true,
    enhancements: [],
}

export const splintMailArmor: Armor = {
    uniqueId: "splintMailArmor",
    name: "Splint Mail Armor",
    arcaneSpellFailureChance: 40,
    armorCheckPenalty: -7,
    baseArmorBonus: 6,
    enhancementBonus: 0,
    maxDexBonus: 0,
    speed20: 15,
    speed30: 20,
    itemType: "ARMOR",
    weight: 45,
    description: "Splint Mail Armor",
    cost: 200,
    equipped: true,
    equipable: true,
    enhancements: [],

}

export const bandedMailArmor: Armor = {
    uniqueId: "bandedMailArmor",
    name: "Banded Mail Armor",
    arcaneSpellFailureChance: 35,
    armorCheckPenalty: -6,
    baseArmorBonus: 6,
    enhancementBonus: 0,
    maxDexBonus: 1,
    speed20: 15,
    speed30: 20,
    itemType: "ARMOR",
    weight: 35,
    description: "Banded Mail Armor",
    cost: 250,
    equipped: true,
    equipable: true,
    enhancements: [],
}

export const halfPlateArmor: Armor = {
    uniqueId: "halfPlateArmor",
    name: "Half Plate Armor",
    arcaneSpellFailureChance: 40,
    armorCheckPenalty: -7,
    baseArmorBonus: 7,
    enhancementBonus: 0,
    maxDexBonus: 0,
    speed20: 15,
    speed30: 20,
    itemType: "ARMOR",
    weight: 40,
    description: "Half Plate Armor",
    cost: 600,
    equipped: true,
    equipable: true,
    enhancements: [],
}

export const fullPlateArmor: Armor = {
    uniqueId: "fullPlateArmor",
    name: "Full Plate Armor",
    arcaneSpellFailureChance: 50,
    armorCheckPenalty: -8,
    baseArmorBonus: 8,
    enhancementBonus: 0,
    maxDexBonus: 1,
    speed20: 15,
    speed30: 20,
    itemType: "ARMOR",
    weight: 50,
    description: "Full Plate Armor",
    cost: 1500,
    equipped: true,
    equipable: true,
    enhancements: [],
}

export const bucklerShield: Shield = {
    uniqueId: "bucklerShield",
    name: "Buckler Shield",
    arcaneSpellFailureChance: 5,
    armorCheckPenalty: -1,
    baseShieldBonus: 1,
    enhancementBonus: 0,
    itemType: "SHIELD",
    weight: 5,
    description: "Buckler Shield",
    cost: 15,
    equipped: true,
    equipable: true,
    enhancements: [],
}

export const lightWoodenShield: Shield = {
    uniqueId: "lightWoodenShield",
    name: "Light Wooden Shield",
    arcaneSpellFailureChance: 5,
    armorCheckPenalty: -1,
    baseShieldBonus: 1,
    enhancementBonus: 0,
    itemType: "SHIELD",
    weight: 6,
    description: "Light Wooden Shield",
    cost: 3,
    equipped: true,
    equipable: true,
    enhancements: [],
}

export const lightSteelShield: Shield = {
    uniqueId: "lightSteelShield",
    name: "Light Steel Shield",
    arcaneSpellFailureChance: 10,
    armorCheckPenalty: -1,
    baseShieldBonus: 1,
    enhancementBonus: 0,
    itemType: "SHIELD",
    weight: 7,
    description: "Light Steel Shield",
    cost: 9,
    equipped: true,
    equipable: true,
    enhancements: [],
}

export const heavyWoodenShield: Shield = {
    uniqueId: "heavyWoodenShield",
    name: "Heavy Wooden Shield",
    arcaneSpellFailureChance: 5,
    armorCheckPenalty: -2,
    baseShieldBonus: 2,
    enhancementBonus: 0,
    itemType: "SHIELD",
    weight: 10,
    description: "Heavy Wooden Shield",
    cost: 7,
    equipped: true,
    equipable: true,
    enhancements: [],
}

export const heavySteelShield: Shield = {
    uniqueId: "heavySteelShield",
    name: "Heavy Steel Shield",
    arcaneSpellFailureChance: 10,
    armorCheckPenalty: -2,
    baseShieldBonus: 2,
    enhancementBonus: 0,
    itemType: "SHIELD",
    weight: 15,
    description: "Heavy Steel Shield",
    cost: 20,
    equipped: true,
    equipable: true,
    enhancements: [],
}

export const towerShield: Shield = {
    uniqueId: "towerShield",
    name: "Tower Shield",
    arcaneSpellFailureChance: 15,
    armorCheckPenalty: -10,
    baseShieldBonus: 4,
    enhancementBonus: 0,
    maxDexBonus: 2,
    itemType: "SHIELD",
    weight: 30,
    description: "Tower Shield",
    cost: 30,
    equipped: true,
    equipable: true,
    enhancements: [],
}