import { MeleeWeapon, RangedWeapon } from "../../core/domain/weapons/weapon";

export const bastardSword: MeleeWeapon = {
  name: "Bastard sword",
  itemType: "WEAPON",
  uniqueId: "bastard-sword",
  damageDice: "1d10",
  weaponAttackType: "melee",
  proficiencyType: "martial",
  defaultWieldType: "twoHanded",
  damageType: {
    type: "basic",
    damageType: "slashing",
  },
  size: "MEDIUM",
  isMasterwork: false,
  baseCritRange: 19,
  changes: [],
  description: "",
  specialChanges: [],
  twoHanded: true,
  weightType: "HEAVY",
  weight: 6,
  baseCritMultiplier: 2,
  enhancements: [],
  finesse: false,
  reachRange: undefined,
  thrown: false,
  thrownRange: undefined,
  equippedChanges: [],
  equippedContextChanges: [],
  wieldedChanges: [],
  wieldedContextChanges: [],
  equipable: true,
  equipped: true,
  wielded: true,
};

export const rapier: MeleeWeapon = {
  name: "Rapier",
  itemType: "WEAPON",
  uniqueId: "rapier",
  damageDice: "1d6",
  weaponAttackType: "melee",
  proficiencyType: "martial",
  defaultWieldType: "primary",
  damageType: {
    type: "basic",
    damageType: "piercing",
  },
  size: "MEDIUM",
  isMasterwork: false,
  baseCritRange: 18,
  changes: [],
  description: "",
  specialChanges: [],
  twoHanded: false,
  weightType: "LIGHT",
  weight: 2,
  baseCritMultiplier: 2,
  enhancements: [],
  finesse: true,
  reachRange: undefined,
  thrown: false,
  thrownRange: undefined,
  equippedChanges: [],
  equippedContextChanges: [],
  wieldedChanges: [],
  wieldedContextChanges: [],
  equipable: true,
  equipped: true,
  wielded: true,
};

export const longBow: RangedWeapon = {
  name: "Longbow",
  itemType: "WEAPON",
  uniqueId: "longbow",
  damageDice: "1d8",
  weaponAttackType: "ranged",
  proficiencyType: "martial",
  defaultWieldType: "primary",
  damageType: {
    type: "basic",
    damageType: "piercing",
  },
  size: "MEDIUM",
  isMasterwork: false,
  baseCritRange: 20,
  changes: [],
  description: "",
  specialChanges: [],
  rangeIncrement: 100,
  ammunitionType: "ARROW",
  requiresLoading: false,
  baseCritMultiplier: 3,
  twoHanded: true,
  weight: 3,
  enhancements: [],
  equippedChanges: [],
  equippedContextChanges: [],
  wieldedChanges: [],
  wieldedContextChanges: [],
  equipable: true,
  equipped: true,
  wielded: true,
};

export const mace: MeleeWeapon = {
  name: "Mace, heavy",
  itemType: "WEAPON",
  uniqueId: "maceHeavy",
  damageDice: "1d8",
  weaponAttackType: "melee",
  proficiencyType: "martial",
  defaultWieldType: "primary",
  damageType: {
    type: "basic",
    damageType: "bludgeoning",
  },
  size: "MEDIUM",
  isMasterwork: false,
  baseCritRange: 20,
  changes: [],
  description: "",
  specialChanges: [],
  twoHanded: false,
  weightType: "HEAVY",
  weight: 8,
  baseCritMultiplier: 2,
  enhancements: [],
  finesse: false,
  thrown: false,
  equippedChanges: [],
  equippedContextChanges: [],
  wieldedChanges: [],
  wieldedContextChanges: [],
  equipable: true,
  equipped: true,
  wielded: true,
};

export const greatAxe: MeleeWeapon = {
  name: "Great axe",
  itemType: "WEAPON",
  uniqueId: "greatAxe",
  damageDice: "3d6",
  weaponAttackType: "melee",
  proficiencyType: "martial",
  defaultWieldType: "twoHanded",
  damageType: {
    type: "basic",
    damageType: "slashing",
  },
  size: "LARGE",
  isMasterwork: false,
  baseCritRange: 20,
  changes: [],
  description: "",
  specialChanges: [],
  twoHanded: true,
  weightType: "HEAVY",
  weight: 12,
  baseCritMultiplier: 3,
  enhancements: [],
  finesse: false,
  thrown: false,
  equippedChanges: [],
  equippedContextChanges: [],
  wieldedChanges: [],
  wieldedContextChanges: [],
  equipable: true,
  equipped: true,
  wielded: true,
};
