/**
 * D&D 3.5 Example Spells
 */

import type { StandardEntity } from '../../../entities/types/base';

export const exampleSpells: StandardEntity[] = [
  {
    id: 'spell-fireball',
    entityType: 'spell',
    name: 'Bola de Fuego',
    description: 'Una explosión de fuego que inflige 1d6 puntos de daño por nivel de lanzador (máximo 10d6) a todas las criaturas en un radio de 6 metros.',
    level: 3,
    school: 'Evocación',
    subschool: 'Fuego',
    components: ['V', 'S', 'M'],
    castingTime: 'Acción estándar',
    range: 'Largo (120 m + 12 m/nivel)',
    duration: 'Instantáneo',
    area: 'Radio de 6 m',
    savingThrow: 'Reflejos a mitad',
    spellResistance: true,
    classes: ['Mago', 'Hechicero'],
    tags: ['daño', 'área', 'fuego'],
  } as StandardEntity,
  {
    id: 'spell-cure-light-wounds',
    entityType: 'spell',
    name: 'Curar Heridas Leves',
    description: 'Restaura 1d8+1 puntos de golpe (más 1 punto por nivel de lanzador, máximo +5).',
    level: 1,
    school: 'Conjuración',
    subschool: 'Curación',
    components: ['V', 'S'],
    castingTime: 'Acción estándar',
    range: 'Toque',
    duration: 'Instantáneo',
    spellResistance: false,
    classes: ['Clérigo', 'Druida', 'Paladín'],
    tags: ['curación', 'toque'],
  } as StandardEntity,
  {
    id: 'spell-invisibility',
    entityType: 'spell',
    name: 'Invisibilidad',
    description: 'El sujeto se vuelve invisible. La invisibilidad termina si el sujeto ataca o lanza un conjuro.',
    level: 2,
    school: 'Ilusión',
    subschool: 'Falsa Visión',
    components: ['V', 'S', 'M'],
    castingTime: 'Acción estándar',
    range: 'Personal o Toque',
    duration: '1 minuto/nivel',
    spellResistance: false,
    classes: ['Mago', 'Hechicero', 'Bardo'],
    tags: ['utilidad', 'sigilo'],
  } as StandardEntity,
  {
    id: 'spell-magic-missile',
    entityType: 'spell',
    name: 'Proyectil Mágico',
    description: 'Un proyectil de energía mágica que inflige 1d4+1 puntos de daño. Crea un proyectil adicional cada 2 niveles (máximo 5 proyectiles).',
    level: 1,
    school: 'Evocación',
    components: ['V', 'S'],
    castingTime: 'Acción estándar',
    range: 'Medio (30 m + 3 m/nivel)',
    duration: 'Instantáneo',
    effect: 'Hasta 5 proyectiles, cada uno inflige 1d4+1 puntos de daño',
    spellResistance: true,
    classes: ['Mago', 'Hechicero'],
    tags: ['daño', 'fuerza'],
  } as StandardEntity,
  {
    id: 'spell-shield',
    entityType: 'spell',
    name: 'Escudo',
    description: 'Una barrera invisible de fuerza que proporciona +4 a la CA y protege contra proyectiles mágicos.',
    level: 1,
    school: 'Abjuración',
    components: ['V', 'S'],
    castingTime: 'Acción estándar',
    range: 'Personal',
    duration: '1 minuto/nivel',
    spellResistance: false,
    classes: ['Mago', 'Hechicero'],
    tags: ['defensivo', 'protección'],
  } as StandardEntity,
  {
    id: 'spell-detect-magic',
    entityType: 'spell',
    name: 'Detectar Magia',
    description: 'Detecta la presencia de magia. Puedes determinar la fuerza y escuela de cada aura mágica.',
    level: 0,
    school: 'Adivinación',
    components: ['V', 'S'],
    castingTime: 'Acción estándar',
    range: '18 m',
    duration: 'Concentración, hasta 1 minuto/nivel',
    area: 'Cubo de 18 m',
    spellResistance: false,
    classes: ['Mago', 'Hechicero', 'Bardo', 'Clérigo', 'Druida'],
    tags: ['detección', 'utilidad'],
  } as StandardEntity,
  {
    id: 'spell-lightning-bolt',
    entityType: 'spell',
    name: 'Rayo',
    description: 'Un rayo de electricidad que inflige 1d6 puntos de daño por nivel de lanzador (máximo 10d6) a todas las criaturas en una línea.',
    level: 3,
    school: 'Evocación',
    subschool: 'Electricidad',
    components: ['V', 'S', 'M'],
    castingTime: 'Acción estándar',
    range: 'Medio (30 m + 3 m/nivel)',
    duration: 'Instantáneo',
    effect: 'Línea de 9 m',
    savingThrow: 'Reflejos a mitad',
    spellResistance: true,
    classes: ['Mago', 'Hechicero'],
    tags: ['daño', 'electricidad', 'línea'],
  } as StandardEntity,
  {
    id: 'spell-bless',
    entityType: 'spell',
    name: 'Bendecir',
    description: 'Otorga +1 de bonificador a las tiradas de ataque y a las tiradas de salvación contra miedos a todos los aliados en un radio de 15 m.',
    level: 1,
    school: 'Encantamiento',
    subschool: 'Compulsión',
    components: ['V', 'S', 'D'],
    castingTime: 'Acción estándar',
    range: '15 m',
    duration: '1 minuto',
    area: 'Todos los aliados en un radio de 15 m',
    spellResistance: false,
    classes: ['Clérigo', 'Paladín'],
    tags: ['bendición', 'bonificador'],
  } as StandardEntity,
  {
    id: 'spell-mage-armor',
    entityType: 'spell',
    name: 'Armadura de Mago',
    description: 'Una armadura invisible de fuerza que proporciona +4 a la CA contra ataques corpóreos.',
    level: 1,
    school: 'Conjuración',
    subschool: 'Creación',
    components: ['V', 'S', 'F'],
    castingTime: 'Acción estándar',
    range: 'Toque',
    duration: '1 hora/nivel',
    spellResistance: false,
    classes: ['Mago', 'Hechicero'],
    tags: ['defensivo', 'armadura'],
  } as StandardEntity,
  {
    id: 'spell-charm-person',
    entityType: 'spell',
    name: 'Hechizar Persona',
    description: 'Hace que una criatura humanoide te considere un amigo de confianza. La criatura obtiene +5 a la tirada de salvación si eres o has sido amenazante.',
    level: 1,
    school: 'Encantamiento',
    subschool: 'Compulsión',
    components: ['V', 'S'],
    castingTime: 'Acción estándar',
    range: 'Cercano (7.5 m + 1.5 m/nivel)',
    duration: '1 hora/nivel',
    target: 'Una criatura humanoide',
    savingThrow: 'Voluntad anula',
    spellResistance: true,
    classes: ['Mago', 'Hechicero', 'Bardo'],
    tags: ['encantamiento', 'social'],
  } as StandardEntity,
];

